### PR TITLE
prefixset: use struct{} as value

### PR DESCRIPTION
**Pull request by database64128**
The value is never used. Change from bool to struct{} to shave off 8 bytes (on 64-bit platforms).

### CODE REVIEW

**Comment by aromatt** [comment]
@database64128 thanks for another solid contribution!

I am testing the impact of this optimization using https://github.com/gaissmai/iprbench. `netipds` is already competitive in memory usage, so I'm excited to see how good it can get.

Regarding the small refactor of `filter` and `filterCopy`: it makes total sense. I'm juggling a few different ideas for cleaning up the types, and I'm not settled on a direction yet. Are you ok with holding off on this change for now?

For now, I'm totally fine with this:
```diff
-func (t *tree[T]) filter(o *tree[bool]) {
+func (t *tree[T]) filter(o *tree[struct{}]) {

```
because it's no worse than it was.

Your new version is more flexible, I'd just like to hold off and make a more atomic, deliberate move.

**Comment by aromatt** [comment]
Benchmark shows an average reduction of almost 25%, which is even better than I expected. Nice!
```
                         │ netipds/size_bool.bm │     netipds/size_emptystruct.bm      │
                         │        bytes         │     bytes      vs base               │
Tier1PfxSize/100                  16.83Ki ± 10%   13.81Ki ± 12%  -17.92% (p=0.002 n=6)
Tier1PfxSize/1_000               128.26Ki ±  1%   97.04Ki ±  2%  -24.34% (p=0.002 n=6)
Tier1PfxSize/10_000              1249.9Ki ±  0%   938.3Ki ±  0%  -24.93% (p=0.002 n=6)
Tier1PfxSize/100_000             11.992Mi ±  0%   8.995Mi ±  0%  -24.99% (p=0.002 n=6)
Tier1PfxSize/1_000_000           112.77Mi ±  0%   84.58Mi ±  0%  -25.00% (p=0.002 n=6)
RandomPfx4Size/100                16.20Ki ± 10%   13.09Ki ± 12%  -19.19% (p=0.002 n=6)
RandomPfx4Size/1_000             127.76Ki ±  1%   96.80Ki ±  2%  -24.23% (p=0.002 n=6)
RandomPfx4Size/10_000            1223.9Ki ±  0%   918.3Ki ±  0%  -24.97% (p=0.002 n=6)
RandomPfx4Size/100_000           10.997Mi ±  0%   8.250Mi ±  0%  -24.98% (p=0.002 n=6)
RandomPfx4Size/1_000_000          92.42Mi ±  0%   69.31Mi ±  0%  -25.00% (p=0.002 n=6)
RandomPfx6Size/100                16.14Ki ± 10%   13.05Ki ± 13%  -19.17% (p=0.002 n=6)
RandomPfx6Size/1_000             127.88Ki ±  1%   96.90Ki ±  2%  -24.23% (p=0.002 n=6)
RandomPfx6Size/10_000            1237.7Ki ±  0%   928.7Ki ±  0%  -24.96% (p=0.002 n=6)
RandomPfx6Size/100_000           11.784Mi ±  0%   8.841Mi ±  0%  -24.97% (p=0.002 n=6)
RandomPfx6Size/1_000_000         114.47Mi ±  0%   85.85Mi ±  0%  -25.00% (p=0.002 n=6)
RandomPfxSize/100                 16.14Ki ± 10%   13.05Ki ± 13%  -19.17% (p=0.002 n=6)
RandomPfxSize/1_000              127.63Ki ±  1%   96.76Ki ±  2%  -24.19% (p=0.002 n=6)
RandomPfxSize/10_000             1228.3Ki ±  0%   920.4Ki ±  0%  -25.06% (p=0.002 n=6)
RandomPfxSize/100_000            11.165Mi ±  0%   8.379Mi ±  0%  -24.95% (p=0.002 n=6)
RandomPfxSize/1_000_000           97.18Mi ±  0%   72.88Mi ±  0%  -25.00% (p=0.002 n=6)
geomean                           1.234Mi         964.7Ki        -23.65%

```

**Comment by aromatt** [comment]
I'm experimenting with rearranging the order of fields in `tree`. I realized that the `bool` used by `PrefixSet` only actually requires one byte, but because of its position in the struct, there are 7 extra bytes of padding.

So, rearranging `tree` to:
```go
type tree[T any] struct {
        key      key
        hasEntry bool
        value    T
        left     *tree[T]
        right    *tree[T]
}
```
We get an almost identical reduction in size:
```
goos: linux
goarch: amd64
cpu: AMD EPYC 7R32
                         │ netipds/size_bool.bm │       netipds/size_packtree.bm       │
                         │        bytes         │     bytes      vs base               │
Tier1PfxSize/100                  16.83Ki ± 10%   13.81Ki ± 12%  -17.92% (p=0.002 n=6)
Tier1PfxSize/1_000               128.26Ki ±  1%   97.04Ki ±  2%  -24.34% (p=0.002 n=6)
Tier1PfxSize/10_000              1249.9Ki ±  0%   938.3Ki ±  0%  -24.93% (p=0.002 n=6)
Tier1PfxSize/100_000             11.992Mi ±  0%   8.995Mi ±  0%  -24.99% (p=0.002 n=6)
Tier1PfxSize/1_000_000           112.77Mi ±  0%   84.58Mi ±  0%  -25.00% (p=0.002 n=6)
RandomPfx4Size/100                16.20Ki ± 10%   13.09Ki ± 13%  -19.19% (p=0.002 n=6)
RandomPfx4Size/1_000             127.76Ki ±  1%   96.52Ki ±  2%  -24.45% (p=0.002 n=6)
RandomPfx4Size/10_000            1223.9Ki ±  0%   918.9Ki ±  0%  -24.93% (p=0.002 n=6)
RandomPfx4Size/100_000           10.997Mi ±  0%   8.257Mi ±  0%  -24.91% (p=0.002 n=6)
RandomPfx4Size/1_000_000          92.42Mi ±  0%   69.31Mi ±  0%  -25.00% (p=0.002 n=6)
RandomPfx6Size/100                16.14Ki ± 10%   13.05Ki ± 13%  -19.17% (p=0.002 n=6)
RandomPfx6Size/1_000             127.88Ki ±  1%   96.80Ki ±  2%  -24.30% (p=0.002 n=6)
RandomPfx6Size/10_000            1237.7Ki ±  0%   929.5Ki ±  0%  -24.90% (p=0.002 n=6)
RandomPfx6Size/100_000           11.784Mi ±  0%   8.832Mi ±  0%  -25.05% (p=0.002 n=6)
RandomPfx6Size/1_000_000         114.47Mi ±  0%   85.85Mi ±  0%  -25.00% (p=0.002 n=6)
RandomPfxSize/100                 16.14Ki ± 10%   13.05Ki ± 13%  -19.17% (p=0.002 n=6)
RandomPfxSize/1_000              127.63Ki ±  1%   96.90Ki ±  2%  -24.08% (p=0.002 n=6)
RandomPfxSize/10_000             1228.3Ki ±  0%   920.2Ki ±  0%  -25.08% (p=0.002 n=6)
RandomPfxSize/100_000            11.165Mi ±  0%   8.376Mi ±  0%  -24.98% (p=0.002 n=6)
RandomPfxSize/1_000_000           97.18Mi ±  0%   72.88Mi ±  0%  -25.00% (p=0.002 n=6)
geomean                           1.234Mi         964.6Ki        -23.66%
```

You can use `unsafe.Offsetof` and `unsafe.Sizeof` to confirm the effect.

Before rearranging:
```
tree[bool] layout:
  key:      0
  value:    24
  left:     32
  right:    40
  hasEntry: 48
Total size: 56 bytes

tree[struct{}] layout:
  key:      0
  left:     24
  right:    32
  hasEntry: 40
Total size: 48 bytes
```

After rearranging:
```
tree[bool] layout:
  key:      0
  hasEntry: 24
  value:    25
  left:     32
  right:    40
Total size: 48 bytes

tree[struct{}] layout:
  key:      0
  hasEntry: 24
  left:     32
  right:    40
Total size: 48 bytes
```

I think I will make this change; we get the same memory savings for `PrefixSet`, and `PrefixMap` will benefit as well.

**Comment by database64128** [comment]
Great discovery! Although `PrefixMap` can only benefit if the value type is smaller than the word size, overall I think it’s worth the layout change. Now that this is down to personal preference, I tend to use the empty struct to signify that the value is unused, like how hash sets are defined with `map[key]struct{}`, but feel free to close this PR if you prefer to keep the value type as-is.

**Comment by aromatt** [comment]
Thanks, I was pleasantly surprised!

> `PrefixMap` can only benefit if the value type is smaller than the word size

True - that includes bools and small integer types, which could be useful.

Anyway, I'm working on some larger changes to how the tree is stored in pursuit of even better space efficiency and lookup times. If after these changes `PrefixSet` still needs to specify a type, I'll definitely use the empty struct.

**Pull request closed without merging**
